{"name": "test_add_member_fail[user2-11528872802-手机已存在于通讯录，无法添加]", "status": "failed", "statusDetails": {"message": "AssertionError: \nExpected: '手机已存在于通讯录，无法添加'\n     but: was <None>", "trace": "self = <testcases.test_addMember.TestAddMember object at 0x000001A3F3E82D30>\nuser = 'user2', phone = '11528872802', expect = '手机已存在于通讯录，无法添加'\n\n    @pytest.mark.parametrize(\"user,phone,expect\", test_data['test_add_member_fail'])\n    def test_add_member_fail(self, user, phone, expect):\n        fail_text = self.addMember.add_member_fail(user, phone)\n>       assert_that(fail_text, equal_to(expect))\nE       AssertionError: \nE       Expected: '手机已存在于通讯录，无法添加'\nE            but: was <None>\n\ntestcases\\test_addMember.py:30: AssertionError"}, "attachments": [{"name": "log", "source": "25b77453-bcf4-46fc-aaf8-b46ba109f2ae-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "'user2'"}, {"name": "phone", "value": "'11528872802'"}, {"name": "expect", "value": "'手机已存在于通讯录，无法添加'"}], "start": 1626596336129, "stop": 1626596348475, "uuid": "3e7a4801-7b58-47db-8a1f-3f6c934ecdb1", "historyId": "f072b275c56a30d0c23d296fd0a67095", "testCaseId": "b251c483add15ec609094c40b1ea12dc", "fullName": "testcases.test_addMember.TestAddMember#test_add_member_fail", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_addMember"}, {"name": "subSuite", "value": "TestAddMember"}, {"name": "host", "value": "z"}, {"name": "thread", "value": "8432-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_addMember"}]}