{"name": "test_add_member_fail[user2-11528872802-手机已存在于通讯录，无法添加]", "status": "failed", "statusDetails": {"message": "AssertionError: \nExpected: '手机已存在于通讯录，无法添加'\n     but: was <None>", "trace": "self = <testcases.test_addMember.TestAddMember object at 0x0000019CF0E62F98>\nuser = 'user2', phone = '11528872802', expect = '手机已存在于通讯录，无法添加'\n\n    @pytest.mark.parametrize(\"user,phone,expect\", test_data['test_add_member_fail'])\n    def test_add_member_fail(self, user, phone, expect):\n        fail_text = self.addMember.add_member_fail(user, phone)\n>       assert_that(fail_text, equal_to(expect))\nE       AssertionError: \nE       Expected: '手机已存在于通讯录，无法添加'\nE            but: was <None>\n\ntestcases\\test_addMember.py:30: AssertionError"}, "attachments": [{"name": "log", "source": "edea21fa-3a6d-4216-ba91-427d28dd1263-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "'user2'"}, {"name": "phone", "value": "'11528872802'"}, {"name": "expect", "value": "'手机已存在于通讯录，无法添加'"}], "start": 1626596740920, "stop": 1626596752724, "uuid": "1b169ead-14c0-4829-b373-e8e89935e370", "historyId": "f072b275c56a30d0c23d296fd0a67095", "testCaseId": "b251c483add15ec609094c40b1ea12dc", "fullName": "testcases.test_addMember.TestAddMember#test_add_member_fail", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_addMember"}, {"name": "subSuite", "value": "TestAddMember"}, {"name": "host", "value": "z"}, {"name": "thread", "value": "16748-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_addMember"}]}