{"name": "test_add_member_fail[user2-11528872802-手机已存在于通讯录，无法添加]", "status": "passed", "attachments": [{"name": "log", "source": "e99908b0-e36b-4dbf-9538-17daf5bd6910-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "'user2'"}, {"name": "phone", "value": "'11528872802'"}, {"name": "expect", "value": "'手机已存在于通讯录，无法添加'"}], "start": 1626597456504, "stop": 1626597467849, "uuid": "63d3ac74-669e-4f39-83f9-16ca637ffa46", "historyId": "f072b275c56a30d0c23d296fd0a67095", "testCaseId": "b251c483add15ec609094c40b1ea12dc", "fullName": "testcases.test_addMember.TestAddMember#test_add_member_fail", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_addMember"}, {"name": "subSuite", "value": "TestAddMember"}, {"name": "host", "value": "z"}, {"name": "thread", "value": "9848-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_addMember"}]}