{"name": "test_add_member_fail[user2-11528872802-手机已存在于通讯录，无法添加]", "status": "failed", "statusDetails": {"message": "AssertionError: \nExpected: '手机已存在于通讯录，无法添加'\n     but: was <None>", "trace": "self = <testcases.test_addMember.TestAddMember object at 0x0000025809A8BA90>\nuser = 'user2', phone = '11528872802', expect = '手机已存在于通讯录，无法添加'\n\n    @pytest.mark.parametrize(\"user,phone,expect\", test_data['test_add_member_fail'])\n    def test_add_member_fail(self, user, phone, expect):\n        fail_text = self.addMember.add_member_fail(user, phone)\n>       assert_that(fail_text, equal_to(expect))\nE       AssertionError: \nE       Expected: '手机已存在于通讯录，无法添加'\nE            but: was <None>\n\ntestcases\\test_addMember.py:30: AssertionError"}, "attachments": [{"name": "log", "source": "d60c8722-541f-43ba-b236-a1789980c1cc-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "user", "value": "'user2'"}, {"name": "phone", "value": "'11528872802'"}, {"name": "expect", "value": "'手机已存在于通讯录，无法添加'"}], "start": 1626597046034, "stop": 1626597057098, "uuid": "278f73fb-cf2f-4b8d-8d1b-623a20c23008", "historyId": "f072b275c56a30d0c23d296fd0a67095", "testCaseId": "b251c483add15ec609094c40b1ea12dc", "fullName": "testcases.test_addMember.TestAddMember#test_add_member_fail", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "test_addMember"}, {"name": "subSuite", "value": "TestAddMember"}, {"name": "host", "value": "z"}, {"name": "thread", "value": "8144-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.test_addMember"}]}